### ISSUE TITLE
Add ability to customize tag column name

### ISSUE THREAD

**Issue by igor-alexandrov** [jetrockets/metka#1]
Implement logic that will allow to to do the following:

```ruby
class Post < ActiveRecord::Base
  include Metka::Model
  
  has_metka do
    column :tags
    column :skills
  end
end
```

**Comment by Bogda** [comment]
https://github.com/jetrockets/metka/pull/18

We had a conversation, where we've decided, that's the current way of initializing Metka column is more suitable, so we can just close this.
